<?php
/**
 * @block \Webtise\BugSnag\Block\Adminhtml\System\Config\TestEvent
 */
?>
<script>
    require(['prototype'], function() {
        //<![CDATA[
            function testEvent() {
                var testResult = $('test_result');

                params = {
                    apiKey: $('bugsnag_settings_apikey').value,
                    releaseStage: $('bugsnag_settings_release_stage').value
                };

                var result = '<?php /* @escapeNotVerified */ echo __('Error during Test Event.') ?>';

                new Ajax.Request('<?php /* @escapeNotVerified */ echo $block->getAjaxUrl() ?>', {
                    parameters: params,
                    onSuccess: function(transport) {
                        result = 'Sent notification. Visit https://bugsnag.com/ to see it in your dashboard';
                        testResult.removeClassName('hidden').addClassName('success');
                        testResult.update(result);
                    },
                    onFailure: function(transport) {
                        result = "Couldn't send a notification. Double check your API key";
                        testResult.removeClassName('hidden').addClassName('error');
                        testResult.update(result);
                    }
                });
            }
            window.testEvent = testEvent;
        //]]>
    });
</script>
<div class="actions actions-test-bugsnag">
    <div id="test_result" class="message-test hidden"></div>
    <button onclick="javascript:testEvent(); return false;" class="action-test-bugsnag" type="button" id="<?php echo $block->getHtmlId() ?>">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>